name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  lint:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
          targets: wasm32-unknown-unknown
      # Note: Temporarily ignore extra unused type parameters from nightly clippy
      # There is an issue with wasm_bindgen who's fix is not yet released.
      # https://github.com/rustwasm/wasm-bindgen/issues/2774
      - run: >
          cargo +nightly clippy --no-deps -- -D warnings
          -A clippy::extra-unused-type-parameters -Z macro-backtrace

  format:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
          targets: wasm32-unknown-unknown
      - run: cargo +nightly fmt --check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo test

  build_lint_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM code
        run: ./build.sh

      - name: Remove ignore file for serving
        run: rm www/pkg/.gitignore

      - name: Deploy to GH pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
