name: CI Workflow

on:
  push:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM code
        run: ./build.sh

      - name: Remove ignore file for serving
        run: rm www/pkg/.gitignore

      - name: Deploy to GH pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www

  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests
        run: cargo test
