name: CI Workflow

on:
  push:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_lint_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update local Rust toolchain
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy rustfmt --toolchain nightly

      - name: Get toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Lint
        run: |
          cargo +nightly fmt -- --check
          cargo +nightly clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build WASM code
        run: ./build.sh

      - name: Remove ignore file for serving
        run: rm www/pkg/.gitignore

      - name: Deploy to GH pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
